New rules for Owin.StaticFiles for object creation.
aws/porting-assistant-dotnet-datastore pull request #39
Opened 2021-03-04 19:41 UTC by Eruanion

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-09 00:44 UTC, jonlouie requested changes

2021-03-09 00:44 UTC, jonlouie commented on recommendation/microsoft.owin.json
> +          "Description": "Remove the base class for owin middleware, remove the override method modifier for the invoke method, add a new gloable xpression for RequestDelegate _next, initialize it in
Fix typo in `gloable xpression` and consider reformatting "owin middleware" to "OwinMiddleware" as in the original (I think these changes were made in a previous PR as well)

2021-03-09 00:44 UTC, jonlouie commented on recommendation/microsoft.owin.json
> +                "Contains": "RequestDelegate_next=null;//CTAChange",
replace `// CTA Change` with `// PortingAssistant change`

2021-03-09 23:54 UTC, jonlouie submitted a review, later dismissed

2021-03-09 23:54 UTC, jonlouie commented on recommendation/microsoft.owin.json
> +          "Description": "Remove the base class for owin middleware, remove the override method modifier for the invoke method, add a new gloable xpression for RequestDelegate _next, initialize it in
Resolving this convo (corrected in #37)

2021-03-19 15:27 UTC, marknfawaz approved these changes

2021-03-19 15:33 UTC, merged